Phone
WildCodeSchool/reims-0919-js-nytte pull request #49
Opened 2020-01-06 15:21 UTC by Cindie1908

Added ternary on form Display in order to hide logo if there is no text

2020-01-06 15:39 UTC, rocambille requested changes

2020-01-06 15:39 UTC, wasthishelpful commented on back/routes/places.js
> +router.post('/api/file',function(req,res){
/api/files

2020-01-06 15:39 UTC, wasthishelpful commented on back/routes/places.js
> +  var upload = multer({ storage : storage}).single('userFile');
const or let ;)

2020-01-06 15:39 UTC, wasthishelpful commented on back/routes/server.js
> +})
still needed?

2020-01-06 15:39 UTC, wasthishelpful commented on front/src/component/DisplayAdmin.js
> +      {props.camping.email===null? "":
try:

    {props.camping.email===null || <img className="logo" src='https://zupimages.net/up/19/49/jijs.png' alt="logo email"></img>}

2020-01-06 15:39 UTC, wasthishelpful commented on front/src/component/DisplayAdmin.js
> +      {props.camping.email===null? "":
check other ternary operators

2020-01-06 15:39 UTC, wasthishelpful commented on front/src/component/FormAdmin.js
> +              </form>
no form in a form

2020-01-06 16:10 UTC, Cindie1908 commented on front/src/component/DisplayAdmin.js
> +      {props.camping.email===null? "":
Corrected :)

2020-01-07 10:31 UTC, Cindie1908 commented on front/src/component/FormAdmin.js
> +              </form>
corrected :)

2020-01-09 10:49 UTC, closed without merging